@extends('layouts.site')
@php $pageContent = app(\App\Services\Travel\TravelPageContent::class)->for('work_visa'); @endphp
@section('title', 'Work Visa Consultation Preview')
@section('meta_description', 'Demo preview of the work visa consultation and document-preparation flow. No application, payment, employment or sponsorship is created.')
@section('canonical', route('work-visa.apply'))
@section('robots', 'noindex,follow')
@section('body_class', 'egho-page-body')
@push('head')<link rel="stylesheet" href="{{ asset('css/egh-travel-pages.css') }}">@endpush
@section('content')
<main class="egh-travel-page"><div class="egho-shell" style="padding-top:30px">
<header class="egh-section"><span class="egho-eyebrow">WORK VISA CONSULTATION</span><h1 style="font-size:36px;color:#08284d;margin:8px 0">Prepare for a work visa consultation</h1><p style="max-width:800px;color:#667085;line-height:1.7">Review the information normally needed before document preparation. This preview does not create an immigration application, job application, payment or sponsorship request.</p></header>
<x-travel.demo-notice message="Sample content shown for demonstration. All form fields are disabled. Nothing entered here is submitted, stored, charged or sent to an employer or authority." />
<div class="egh-legal-note"><strong>Important:</strong> No job, employer sponsorship, eligibility or visa outcome is guaranteed. The relevant employer and government authority make their own decisions.</div>
<section class="egh-section"><div class="egh-step-grid">@foreach([['01','Route','Choose an intended destination and work-visa route.'],['02','Profile','Review identity, qualification and employment-history details.'],['03','Documents','Prepare the route-specific evidence checklist.'],['04','Consultation','Confirm next steps before any real application process begins.']] as $step)<article class="egh-step"><b>{{ $step[0] }}</b><h3>{{ $step[1] }}</h3><p>{{ $step[2] }}</p></article>@endforeach</div></section>
<section class="egh-section"><div class="egh-info-grid"><article class="egh-info-card" style="grid-column:span 2"><h2>Consultation information preview</h2><div class="egh-search-grid" style="grid-template-columns:1fr 1fr">
<label class="egho-field"><span>Destination</span><select disabled><option>Select destination</option></select></label><label class="egho-field"><span>Work visa route</span><select disabled><option>Select route</option></select></label><label class="egho-field"><span>Full name</span><input disabled placeholder="Applicant name"></label><label class="egho-field"><span>Nationality</span><input disabled placeholder="Nationality"></label><label class="egho-field"><span>Current occupation</span><input disabled placeholder="Occupation"></label><label class="egho-field"><span>Years of experience</span><input disabled placeholder="Experience"></label><label class="egho-field"><span>Email</span><input disabled type="email" placeholder="Email address"></label><label class="egho-field"><span>Phone</span><input disabled type="tel" placeholder="Phone number"></label></div><p style="color:#667085">Demo Preview only — no applicant record is created.</p></article>
<aside class="egh-info-card"><h2>Preview checklist</h2><ul class="egh-list"><li>Passport and identity documents</li><li>Qualifications and certificates</li><li>Employment history / CV</li><li>Language evidence where required</li><li>Genuine employer documents where the chosen route requires sponsorship</li></ul><div style="margin-top:18px"><span class="egh-muted-button" aria-disabled="true">Consultation submission disabled</span></div></aside></div></section>
<section class="egh-section egh-faq"><details><summary>Does this form submit an application?</summary><p>No. It is a disabled Demo Preview of a future consultation flow.</p></details><details><summary>Will I be charged?</summary><p>No. This preview has no payment action and displays no supplier- or authority-confirmed fee.</p></details></section>
<a href="{{ route('work-visa.index') }}" class="egho-btn egho-btn-ghost">Back to Work Visa Processing</a>
</div></main>
@endsection