<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    @php
        $siteName=$siteName??'Eagle Global Hub LTD';$siteTagline=$siteTagline??'Travel & Visa Services';$siteContact=$siteContact??[];$siteSocial=$siteSocial??[];$footerLinks=$footerLinks??[];
        $pageTitle=trim($__env->yieldContent('title','Travel'));$pageDescription=trim($__env->yieldContent('meta_description','Travel and booking services from '.$siteName.'.'));$canonical=trim($__env->yieldContent('canonical',url()->current()));$robots=trim($__env->yieldContent('robots','index,follow'));$ogTitle=trim($__env->yieldContent('og_title',$pageTitle));$ogDescription=trim($__env->yieldContent('og_description',$pageDescription));$ogImage=trim($__env->yieldContent('og_image',''));$twitterCard=trim($__env->yieldContent('twitter_card','summary_large_image'));$fullTitle=request()->routeIs('home')?$pageTitle:$pageTitle.' | '.$siteName;
        $themeCss=static function(string $file):string{$modifiedAt=@filemtime(public_path($file));return asset($file).($modifiedAt?'?v='.$modifiedAt:'');};
        $travelServices=$travelServices??[];$serviceLinkIsAllowed=static function(array $service):bool{if(!($service['available']??false)||empty($service['route_name']))return false;$permission=$service['permission']??null;return !$permission||(auth()->check()&&auth()->user()->can($permission));};
        $navIcons=['flights'=>'<path d="M3 13.5 21 5l-3.5 8.5L21 19z"/><path d="M8.5 12.2 3 13.5"/>','hotels'=>'<path d="M4 20V9m0 5h16v6M4 9l8-5 8 5"/><path d="M9.5 14.5v-2h5v2"/>','tours'=>'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.4 2.5 3.6 5.5 3.6 9s-1.2 6.5-3.6 9c-2.4-2.5-3.6-5.5-3.6-9S9.6 5.5 12 3z"/>','visa'=>'<path d="M6 3h9l4 4v14H6z"/><path d="M14.5 3v4.5H19"/><path d="M9 13h6M9 16.5h4"/>'];
    @endphp
    <title>{{ $fullTitle }}</title><meta name="description" content="{{ $pageDescription }}"><meta name="robots" content="{{ $robots }}"><link rel="canonical" href="{{ $canonical }}">
    <meta property="og:type" content="website"><meta property="og:site_name" content="{{ $siteName }}"><meta property="og:title" content="{{ $ogTitle ?: $fullTitle }}"><meta property="og:description" content="{{ $ogDescription ?: $pageDescription }}"><meta property="og:url" content="{{ $canonical }}">@if($ogImage)<meta property="og:image" content="{{ $ogImage }}">@endif
    <meta name="twitter:card" content="{{ $twitterCard }}"><meta name="twitter:title" content="{{ $ogTitle ?: $fullTitle }}"><meta name="twitter:description" content="{{ $ogDescription ?: $pageDescription }}">@if($ogImage)<meta name="twitter:image" content="{{ $ogImage }}">@endif
    @vite(['resources/css/app.css','resources/js/app.js']) {{ Vite::fonts() }}
    <link rel="stylesheet" href="{{ $themeCss('css/egh-ota.css') }}"><link rel="stylesheet" href="{{ $themeCss('css/egh-workspace.css') }}"><link rel="stylesheet" href="{{ $themeCss('css/egh-chrome.css') }}"><link rel="stylesheet" href="{{ $themeCss('css/egh-home-dynamic.css') }}">@stack('head')
</head>
<body class="site-body @yield('body_class')"><a href="#main-content" class="site-skip-link">Skip to content</a>
<header class="egho-header-shell">
<div class="egho-topbar"><div class="egho-shell egho-topbar-inner"><div class="egho-topbar-group">
@feature('support')<a class="egho-topbar-item" href="{{ route('support') }}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 4.5 6.6v4.9c0 4.6 3.1 7.6 7.5 8.5 4.4-.9 7.5-3.9 7.5-8.5V6.6z"/><path d="m9 12 2.2 2.2L15.5 10"/></svg><strong>Customer Support</strong></a>@endfeature
@if(data_get($siteContact,'phone'))<a class="egho-topbar-item" href="tel:{{ preg_replace('/[^+0-9]/','',data_get($siteContact,'phone')) }}">{{ data_get($siteContact,'phone') }}</a>@endif
@if(data_get($siteContact,'email'))<a class="egho-topbar-item" href="mailto:{{ data_get($siteContact,'email') }}">{{ data_get($siteContact,'email') }}</a>@endif
@if(!data_get($siteContact,'phone')&&!data_get($siteContact,'email'))<span class="egho-topbar-item">Official contact channels are not configured yet</span>@endif
</div><div class="egho-topbar-group"><div class="egho-topbar-group egho-topbar-group-toplinks">@feature('about')<a class="egho-topbar-item" href="{{ route('about') }}">Offers</a>@endfeature @feature('support')<a class="egho-topbar-item" href="{{ route('support') }}">Help</a>@endfeature @feature('bookings')@can('flights.book')<a class="egho-topbar-item" href="{{ route('bookings.index') }}">Manage Booking</a>@else @auth<a class="egho-topbar-item" href="{{ route('dashboard') }}">Manage Booking</a>@endauth @endcan @endfeature</div><div class="egho-topbar-group egho-topbar-group-locale"><span class="egho-switch">EN</span><span class="egho-switch">BDT</span></div>@auth @feature('account')<a href="{{ route('account.overview') }}" class="egho-user-chip"><span class="egho-user-avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><span class="egho-user-copy"><strong>{{ auth()->user()->name }}</strong><small>My Account</small></span></a>@endfeature<form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="site-button site-button-ghost">Logout</button></form>@else<a href="{{ route('login') }}" class="site-button site-button-ghost">Login</a><a href="{{ route('register') }}" class="site-button site-button-primary">Sign Up</a>@endauth</div></div></div>
<div class="egho-header"><div class="egho-shell egho-header-inner"><a href="{{ route('home') }}" class="egho-brand" aria-label="{{ $siteName }} home">@if(!empty($siteLogo))<img class="egho-brand-logo" src="{{ $siteLogo }}" alt="{{ $siteName }} logo">@else<span class="egho-brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M21 3.6c.5-1.2-1.3-2.4-2.2-1.4L14.6 7 6.9 4.2a1 1 0 0 0-1.2.4L4 7.2a1 1 0 0 0 .5 1.5l6.2 1.9-2.9 3.3-2.6-.4a1 1 0 0 0-.9.3L3 15.4a1 1 0 0 0 .6 1.6l4.2 1.1 1.1 4.2a1 1 0 0 0 1.6.6l1.6-1.3a1 1 0 0 0 .3-.9l-.4-2.6 3.3-2.9 1.9 6.2a1 1 0 0 0 1.5.5l2.6-1.7a1 1 0 0 0 .4-1.2L18.9 13l4.8-4.2c.1-.1.2-.2.3-.3z"/></svg></span><span class="egho-brand-copy"><strong>{{ $siteName }}</strong><small>{{ $siteTagline }}</small></span>@endif</a>
<nav class="egho-nav" aria-label="Primary navigation">@feature('flights')@can('flights.search')<a href="{{ route('flights.index') }}" @class(['is-active'=>request()->routeIs('flights.*')])><svg viewBox="0 0 24 24">{!! $navIcons['flights'] !!}</svg>Flights</a>@else @auth<a href="{{ route('dashboard') }}"><svg viewBox="0 0 24 24">{!! $navIcons['flights'] !!}</svg>Flights</a>@else<a href="{{ route('login') }}"><svg viewBox="0 0 24 24">{!! $navIcons['flights'] !!}</svg>Flights</a>@endauth @endcan @endfeature @foreach($travelServices as $serviceKey=>$service)@feature($serviceKey)@if($serviceKey!=='flights'&&$serviceLinkIsAllowed($service))<a href="{{ route($service['route_name']) }}" @class(['is-active'=>request()->routeIs($serviceKey.'.*')])><svg viewBox="0 0 24 24">{!! $navIcons[$serviceKey]??$navIcons['visa'] !!}</svg>{{ $service['label'] }}</a>@endif @endfeature @endforeach @feature('visa')<a href="{{ route('work-visa.index') }}" @class(['is-active'=>request()->routeIs('work-visa.*')])>Work Visa<span class="egho-nav-badge">New</span></a>@endfeature<details class="egho-nav-more"><summary>More</summary><div class="egho-nav-menu"><a href="{{ route('home') }}">Home</a>@feature('about')<a href="{{ route('about') }}">About Us</a>@endfeature @feature('support')<a href="{{ route('support') }}">Help &amp; support</a>@endfeature @auth<a href="{{ route('dashboard') }}">Dashboard</a>@endauth<a href="{{ route('terms') }}">Terms &amp; Conditions</a></div></details></nav></div></div>
</header>
@if(app()->environment(['local','testing'])&&!request()->routeIs('home'))<div class="site-environment-banner" role="status"><strong>Development / sandbox environment:</strong> supplier availability may use fixture or sandbox data and must not be treated as live inventory.</div>@endif
<div id="main-content">@yield('content')</div>
<footer class="egho-footer"><div class="egho-shell"><div class="egho-footer-main"><div><a href="{{ route('home') }}" class="egho-footer-brand">{{ $siteName }}</a><p class="egho-footer-desc">{{ $siteFooterDescription??'' }}</p>@if($siteSocial!==[])<div class="egho-footer-social">@foreach($siteSocial as $network=>$url)<a href="{{ $url }}" target="_blank" rel="noopener noreferrer" aria-label="{{ ucfirst($network) }}">{{ strtoupper(substr($network,0,2)) }}</a>@endforeach</div>@endif</div><div><h3>Quick Links</h3><div class="egho-footer-list"><a href="{{ route('home') }}">Home</a>@feature('about')<a href="{{ route('about') }}">About Us</a>@endfeature @feature('support')<a href="{{ route('support') }}">Contact Us</a>@endfeature<a href="{{ route('terms') }}">Terms &amp; Conditions</a>@foreach($footerLinks as $link)@if(!empty($link['url'])&&!empty($link['title']))<a href="{{ $link['url'] }}">{{ $link['title'] }}</a>@endif @endforeach</div></div><div><h3>Our Services</h3><div class="egho-footer-list">@feature('flights')@can('flights.search')<a href="{{ route('flights.index') }}">Flights</a>@else<a href="{{ auth()->check()?route('dashboard'):route('login') }}">Flights</a>@endcan @endfeature @foreach($travelServices as $serviceKey=>$service)@feature($serviceKey)@if($serviceKey!=='flights'&&$serviceLinkIsAllowed($service))<a href="{{ route($service['route_name']) }}">{{ $service['label'] }}</a>@endif @endfeature @endforeach @feature('visa')<a href="{{ route('work-visa.index') }}">Work Visa Processing</a>@endfeature</div></div><div><h3>Support</h3><div class="egho-footer-list">@feature('support')<a href="{{ route('support') }}">Help Center</a>@endfeature @auth<a href="{{ route('dashboard') }}">Manage Booking</a>@endauth<a href="{{ route('terms') }}">Privacy &amp; Terms</a></div></div><div><h3>Contact Info</h3><ul class="egho-footer-contact">@if(data_get($siteContact,'address'))<li><span>{{ data_get($siteContact,'address') }}</span></li>@endif @if(data_get($siteContact,'phone'))<li><a href="tel:{{ preg_replace('/[^+0-9]/','',data_get($siteContact,'phone')) }}">{{ data_get($siteContact,'phone') }}</a></li>@endif @if(data_get($siteContact,'email'))<li><a href="mailto:{{ data_get($siteContact,'email') }}">{{ data_get($siteContact,'email') }}</a></li>@endif @if(data_get($siteContact,'hours'))<li><span>{{ data_get($siteContact,'hours') }}</span></li>@endif @if(!array_filter($siteContact))<li><span>Official contact channels are not configured yet.</span></li>@endif</ul></div></div><div class="egho-footer-bottom"><small>&copy; {{ now()->year }} {{ $siteName }}. All rights reserved.</small><ul class="egho-footer-status"><li>Secure account &amp; booking steps</li><li>Provider credentials stay server-side</li></ul></div></div></footer>
@stack('scripts')</body></html>
